### ISSUE TITLE
Error on 1.8.8

### ISSUE THREAD

**Issue by BrettPlays** [TheLimeGlass/FunkySk#2]
https://hastebin.com/owotibedaj.cs

**Comment by BrettPlays** [comment]
Same error on 1.12, this plugin is using a class that no longer exists.

**Comment by TheLimeGlass** [comment]
This was a temporary fix I created while Bensku removed the whole slot system. If you install MundoSk. The issue should be fixed until a fix from myself.

**Comment by BrettPlays** [comment]
Using the latest Spigot 1.12.2, 1.8.5 MundoSK and the Latest 1.12.2 Skript (dev37c), I get this on startup from MundoSK: https://hastebin.com/equhahaves.js

**Comment by TheLimeGlass** [comment]
This was actually fixed a long time ago, just haven't made a public update.

**Comment by BrettPlays** [comment]
In MundoSK?  If so, could you give me a download lol. Thanks.
