### ISSUE TITLE
Where do i add FunkySk?

### ISSUE THREAD

**Issue by Spacy-Diego** [TheLimeGlass/FunkySk#7]
Hey, i installed FunkySk so i got the Syntax.md but i don't really know where i should add it i tried adding it in the plugins folder but seemed like it dosn't work then i added it in skript but that also didn't worked. Where do i acutaly add the file/code? Please help me.

**Comment by TheLimeGlass** [comment]
You need to install Skript and yes it goes into the plugin folder.

Skript can be downloaded at https://github.com/SkriptLang/Skript/releases

**Comment by Spacy-Diego** [comment]
Thanks, i already got skript I am pretty good in it but still tahnks for the help.
